function data = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  DATA = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  data = importfile1("/home/micha/Syncthing/informatyka/II stopień/I rok 1 semestr/Eksploracja Danych/Laboratoria/lab3/data.csv", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2020 11:40:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Period", "USdollarEUR"];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Period", "InputFormat", "yyyy-MM-dd");

% Import the data
data = readtable(filename, opts);

end